### ISSUE TITLE
PDF builds

### ISSUE THREAD

**Issue by avivace** [Cinofix/Afternotes#7]
The PDF links in the [README](https://github.com/Cinofix/Afternotes/blob/master/README.md) seems to be broken. Are the PDF builds hosted somewhere else at the moment?

**Comment by Cinofix** [comment]
I'm sorry I'm late! Now you can find the pdf for each course. In the past, I decided to remove PDFs because of their large size, but I totally agree with you that it is more convenient to have a built-version that you can easily download.

**Comment by avivace** [comment]
Great! Thank you!
